"""Students

Revision ID: 0ad245149ad9
Revises: 5161a1e8d409
Create Date: 2021-12-04 18:10:22.123531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad245149ad9'
down_revision = '5161a1e8d409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_teacher', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_name'), 'class', ['name'], unique=True)
    op.create_index(op.f('ix_class_name_teacher'), 'class', ['name_teacher'], unique=True)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('age', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_address'), 'students', ['address'], unique=True)
    op.create_index(op.f('ix_students_age'), 'students', ['age'], unique=True)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=True)
    op.create_index(op.f('ix_students_name'), 'students', ['name'], unique=True)
    op.drop_index('ix_user_email', table_name='user')
    op.drop_index('ix_user_user_name', table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_user_name', 'user', ['user_name'], unique=False)
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_index(op.f('ix_students_name'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_age'), table_name='students')
    op.drop_index(op.f('ix_students_address'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_class_name_teacher'), table_name='class')
    op.drop_index(op.f('ix_class_name'), table_name='class')
    op.drop_table('class')
    # ### end Alembic commands ###
